(setq mac-function-modifier 'super)
(global-set-key "\C-q" 'backward-kill-line)
(global-set-key (kbd "C-x m") 'execute-extended-command)
(global-set-key (kbd "C-z") 'undo)
(global-set-key (kbd "M-v") 'yank)
(global-set-key (kbd "M-s-h") 'enlarge-window-horizontally)
(global-set-key (kbd "M-s-l") 'shrink-window-horizontally)
(global-set-key (kbd "M-s-j") 'enlarge-window)
(global-set-key (kbd "M-s-k") 'shrink-window)
(global-set-key (kbd "s-\\") 'balance-windows)
(global-set-key (kbd "s-u") 'previous-buffer)
(global-set-key (kbd "s-i") 'next-buffer)
(global-set-key (kbd "s-SPC") 'eshell)
(global-set-key (kbd "s-h") 'forward-word)
(global-set-key (kbd "s-l") 'backward-word)
(global-set-key [s-return] 'insert-blank-line-after-current)
(global-set-key (kbd "M-[") 'previous-buffer)
(global-set-key (kbd "M-]")  'next-buffer)
(global-set-key [f5] 'call-last-kbd-macro)
(global-set-key (kbd "C-5") 'call-last-kbd-macro)
(global-set-key "\M-D" 'nav)
(global-set-key (kbd "<C-s-backspace>") 'paredit-mode)
(global-set-key (kbd "<s-right>") 'next-buffer)
(global-set-key (kbd "<s-left>") 'previous-buffer)
(global-set-key (kbd "<s-backspace>") 'viper-mode)
(global-set-key "\C-cp" 'tcrayford-ido-find-config)
(global-set-key "\C-xp" 'tcrayford-ido-find-project)
(global-set-key "\C-xu" 'tcrayford-ido-find-uni)
(global-set-key "\C-m" 'newline-and-indent)
(global-set-key "\M-s" 'save-buffer)
(provide 'bindings)
